# cleaning.R - script for adding koeppen site climate zones and continent data
# Author: Archie Benn
# Date: 04-06-2026

rm(list = ls())

if (!require(kgc)) install.packages("kgc")
library(tidyverse)
library(rnaturalearth)
library(sf)

# read in data
df_06 <- read_csv("data/main/06_ET_plots/adjusted_dates_data.csv")

# 1. continent data
# get continent data for all countries
countries_continents <- ne_countries(scale = "medium", returnclass = "sf") %>%
    select(continent)

# attach continent data by merging
sites_w_cont <- df_06 %>%
    
    # drop duplicate rows of these vars
    distinct(Site_ID, Longitude, Latitude) %>%
    
    # apply sf transformations 
    st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
    # merge sites to continent data
    st_join(., countries_continents, join = st_intersects)



# 2. climate data
# look up vector to simplify climate zones generated by kgc later
koeppen_lookup <- c(
    
    # tropical - constant warm temps
    Af = "Tropical", Am = "Tropical", Aw = "Tropical", As = "Tropical",
    
    # dry - low precip rates
    BSh = "Dry", BSk = "Dry", BWh = "Dry", BWk = "Dry",
    
    # temperate - mild annual temps
    Cfa = "Temperate", Cfb = "Temperate", Cfc = "Temperate",
    Csa = "Temperate", Csb = "Temperate", Csc = "Temperate",
    Cwa = "Temperate", Cwb = "Temperate", Cwc = "Temperate",
    
    # continental - hot summers and cold winters
    Dfa = "Continental", Dfb = "Continental", Dfc = "Continental", Dfd = "Continental",
    Dsa = "Continental", Dsb = "Continental", Dsc = "Continental", Dsd = "Continental",
    Dwa = "Continental", Dwb = "Continental", Dwc = "Continental", Dwd = "Continental",
    
    # polar - constant cold temps
    ET = "Polar", EF = "Polar"
)


# df for determining Koeggen climate zones based off coordinates of sites using kgc library
site_climates <- df_06 %>%
    distinct(Site_ID, Longitude, Latitude) %>%
    mutate(
        rndCoord.lon = RoundCoordinates(Longitude, latlong = "lon"),
        rndCoord.lat = RoundCoordinates(Latitude, latlong = "lat"),
        Climate_zone = LookupCZ(data.frame(Site = Site_ID, Longitude, Latitude, rndCoord.lon, rndCoord.lat))
    ) %>%
    
    # simplify using lookup vector
    mutate(Climate_zone = koeppen_lookup[Climate_zone]) %>%
    
    # attach continent data from above
    left_join(select(sites_w_cont, continent, Site_ID), by = "Site_ID") %>%
    dplyr::rename(., Continent = continent)


# 3. recombining climate and continent data
df_climates <- df_06 %>%
    left_join(select(site_climates, Site_ID, Climate_zone, Continent), by = "Site_ID") %>%
    relocate(Site_ID,                                                            # rearranging columns
             Date, 
             Latitude, 
             Longitude, 
             Continent,
             Cover_type, 
             Climate_zone,
             Site_age,
             ET,
             LE, 
             Lai_500m,
    )



# **********************************************************
# failsafe for site age at a given site where age is known
# was having some issues with the site age changing from masked packages downstream, so adding this to fail the script if the age is false
# this is important as my analysis is very focused on age
# BE-Bra is in full pipeline, so used as reference.
# age expected here is 87.088 as have now back-propagated with decimal (and is in 2005, aged 78 in 1996)
expected_age <- 87.088

actual_age <- df_climates %>%
    filter(Site_ID == "BE-Bra", 
           Date == "2005-02-01") %>%
    pull(Site_age)

# stop execution and paste issue
if (!isTRUE(all.equal(actual_age, expected_age))) {
    stop(paste("BE-Bra site age has drifted from expected value!",
               "\nExpected age:", expected_age,
               "\nActual age:", actual_age))
}
# **********************************************************


# write out
write_csv(df_climates, "data/main/07_climates/climates_data.csv")

print("climates.R complete")


  
    
    
    
    
    
    
    
    
    
    


    
    
    
    
    
    














