---
title: "ML_single_sites.Rmd"
author: "Archie Benn"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

library(tidyverse)
library(here)
library(wesanderson)
library(patchwork)
library(sf)
library(rnaturalearth) 
library(countrycode)
library(ggrepel)
```

# Exploring single site model predictions (GAM/RF/other ML models)
- similar to the earlier `13_GAM_exploration.Rmd`, but alongside other ML models  

- Results are from GAM and RF models trained on 56/57 sites, and predicting ET on the final site  
- In each architecture the same variales were used and removed per model (not identical, as RF had encoded categorical data as this will be used for other ML models which require this in the same .py file)
- GAM results are formed in `12_GAM_formation.R`  
- RF results are formed in `16_ML_single_held_out.py`  

# Load in data
```{R}
df_sites <- read_csv(here("data/main/10_filtering2/df_sites2.csv"))

results_dir <- "data/main/16_ML_results/"

# load in data
GAM_preds <- read.csv(here(paste(results_dir, "GAM_preds_results.csv", sep = "")))
GAM_stats <- read.csv(here(paste(results_dir, "GAM_stats_results.csv", sep = "")))

RF_preds <- read.csv(here(paste(results_dir, "RF_preds_results.csv", sep = "")))
RF_stats <- read.csv(here(paste(results_dir, "RF_stats_results.csv", sep = "")))
RF_shap <- read.csv(here(paste(results_dir, "RF_shap_results.csv", sep = "")))

# set dates to Date type from char
GAM_preds$Date <- as.Date(GAM_preds$Date)
RF_preds$Date <- as.Date(RF_preds$Date)
```

# Form merged dataframes for stats/preds/shap stuff
```{R}
preds_merged <- bind_rows(GAM_preds, RF_preds)

stats_merged <- bind_rows(GAM_stats, RF_stats)
    
shap_merged <- bind_rows(RF_shap)

# rename 'site' to Site_ID in both shap and stats merged dfs
stats_merged <- stats_merged %>%
    rename(Site_ID = site)

shap_merged <- shap_merged %>%
    rename(Site_ID = site)
```

# 1.stats df
## 1.1 R-squared and RMSE across models and architectures  
```{R}
# full spread histgram
p1_r2 <- stats_merged %>%
    
  ggplot(mapping = aes(x = model, y = r2)) +
  
  # violin plot 
  geom_violin(aes(fill = model)) + 
  
  # hide redundant legend
  guides(fill = "none") +
  
  # add boxplot 
  geom_boxplot(width = 0.1, col = "black")+
    
  # aesthetics
  scale_fill_manual(values = wes_palette("AsteroidCity2")) +
  ggtitle("R^2 for all sites across models") +
  theme_minimal() +
  ylab("R^2") + 
  xlab("Model") +
  scale_x_discrete(limits = c("all", "no_lai", "no_age", "no_age_no_lai")) +
    
    facet_wrap(~architecture)

p1_r2
```

## 1.2 RMSE
```{R}
# full spread histgram
p1_r2 <- stats_merged %>%
    
  ggplot(mapping = aes(x = model, y = rmse)) +
  
  # violin plot 
  geom_violin(aes(fill = model)) + 
  
  # hide redundant legend
  guides(fill = "none") +
  
  # add boxplot 
  geom_boxplot(width = 0.1, col = "black")+
    
  # aesthetics
  scale_fill_manual(values = wes_palette("AsteroidCity2")) +
  ggtitle("RMSE for all sites across models") +
  theme_minimal() +
  ylab("R^2") + 
  xlab("Model") +
  scale_x_discrete(limits = c("all", "no_lai", "no_age", "no_age_no_lai")) +
    
    facet_wrap(~architecture)

p1_r2
```

# 2. Observed vs. predicted over time across models
- these functions are the same as in `17_generate_plots.R`, but for single sites to selectively show the chosen plots  
- this last script generated plots in a loop for all sites using similar functions  

```{R}
# function to generate ET vs.time plots for observed and fitted from different architectures
# (model constant, compare architectures)

preds_by_architecture_single <- function(mod, site, data, stats_df){
    
    # get r2 and rmse form stats_df
    stats_sub <- stats_df %>%
        filter(model == mod, Site_ID == site)
    
    # plot ET vs time per site
    p <- data %>%
        
        filter(model == mod) %>%
        filter(Site_ID == site) %>%
        ggplot(aes(x = Date)) +
        
        # fit observed and predicted to same plot
        geom_line(aes(y = observed_ET, colour = "Observed"), alpha = 0.6) +
        geom_line(aes(y = predicted_ET, colour = "Predicted"), alpha = 0.6) +
        
        ylab("Daily ET (mm)") +
            
        ggtitle(paste(site, " (Model: ", mod, ")", sep = "")) +
        
        theme_minimal() +
        
        # legend
        scale_colour_manual(name = "Legend", 
                             values = c("Observed" = "seagreen", "Predicted" = "tomato")) +
            
            
        facet_wrap(~architecture) +
        
        # add stats to plot
        geom_text(data = stats_sub,
                  aes(x = -Inf, y = Inf, 
                      label = paste("R-squared = ", round(r2, 2), 
                                     "\nRMSE = ", round(rmse, 2))),
                  hjust = -0.1, vjust = 1.2,  
                  size = 3) 
    
    p
}

# function do facet by model
# (# architecture constant, compare models)
RF_preds_by_model_single <- function(arch, site, data, stats_df){
    
    # get r2 and rmse form stats_df
    stats_sub <- stats_df %>%
        filter(architecture == arch, Site_ID == site)
    
    # plot ET vs time per site
    p <- data %>%
        
        filter(architecture == arch) %>%
        filter(Site_ID == site) %>%
        ggplot(aes(x = Date)) +
        
        # fit observed and predicted to same plot
        geom_line(aes(y = observed_ET, colour = "Observed"), alpha=0.6) +
        geom_line(aes(y = predicted_ET, colour = "Predicted"), alpha=0.6) +
        
        ylab("Daily ET (mm)") +
            
        ggtitle(paste(arch, "models at", site)) +
        
        # legend
        scale_colour_manual(name = "Legend", 
                             values = c("Observed" = "seagreen", "Predicted" = "tomato")) +
            
            
        facet_wrap(~model) +
        
        # add stats to plot
        geom_text(data = stats_sub,
                  aes(x = -Inf, y = Inf, 
                      label = paste("R-squared = ", round(r2, 2), 
                                     "\nRMSE = ", round(rmse, 2))),
                  hjust = -0.1, vjust = 1.2,  
                  size = 3) +
        
        theme_minimal() 
        
    p
}

```


## 2.2 Example plots from `17_plots_generate.R`  
- some of the more interesting plots which came out of the last script (produces plots for all sites)  

### Constant model, compare across ML architecture:
#### 1. All vs. no age model at CA-Man

```{R, warning = FALSE}
preds_by_architecture_single("all", "CA-Man", preds_merged, stats_merged)
```

- RF performing far better than GAM here, why? 

```{R, warning = FALSE}
preds_by_architecture_single("no_age", "CA-Man", preds_merged, stats_merged)
```

- Same as above without age - GAM can now predict ET far better, so why is age as a feature causing this?  
- and why in GAM but not RF?

#### 2. RF vs. GAM at CA-NS7 all model

```{R, warning = FALSE}
preds_by_architecture_single("all", "CA-NS7", preds_merged, stats_merged)
```

```{R, warning = FALSE}
preds_by_architecture_single("no_age", "CA-NS7", preds_merged, stats_merged)
```

- similar again to CA-Man, no-age model is forming far better predictions compared to the full model in GAM

- RF performing far better than GAM here, why?

### Constant ML architecture, compare scross models:
#### 1. RF at CA-TP1
```{R, warning = FALSE}
RF_preds_by_model_single("RF", "CA-TP1", preds_merged, stats_merged)
```

- Over predicting in earlier years compared to observed - what is happening in these earlier years?    
- Very poor R-squared as a result  


#### 2. RF at US-GBT
```{R, warning = FALSE}
RF_preds_by_model_single("RF", "US-GBT", preds_merged, stats_merged)
```

- here age appears to have a slight positive impact  
- in both models where age was removed the R-squared was reduced and RMSE increased, although this is minor (should test significance)  

### 3. RF at US-Me3
```{R, warning = FALSE}
RF_preds_by_model_single("RF", "US-Me3", preds_merged, stats_merged)
```

- this one is interesting as the model over predicts only when both age and LAI are removed  
- the R-squared is largely reduced and RMSE increased when these are both removed, and much more pronounced compared to removing LAI or age individually (although removing age alone appears to have no real impact)

#### 4. RF at US-NR1
```{R, warning = FALSE}
RF_preds_by_model_single("RF", "US-NR1", preds_merged, stats_merged)
```

- removing age appears to have a positive impact on the predictions at this site with RF  


# 3. SHAP feature importance from the ML models  
- will investigate the importance the models place on individual features here by various factors like climate type, cover type, continent etc.  
- SHAP gives magnitude (+ve and -ve impact on prediction) and is also measure in the response's units (so mm here for ET preds)  
- these SHAP values are based on 100 randomly sampled row predictions and formed in `16_ML_single_held_out.py`  

## 3.1 Global SHAP feature importance at all sites (abs mean)  
- non-directional feature importance means for all feature model across all sites 
- non-directional for all sites version as it stops +ves and -ves cancelling out in mean

```{R}
# select site/architecture/model
ml_arch <- "RF"
ml_model <- "all"

# create df of SHAP score means across features per site
shap_site_summary <- shap_merged %>%
    
    # select chosen rows
    filter(architecture == ml_arch, model == ml_model) %>%
    
    # apply summaries across all columns with everything()
    # ~mean(abs(.x)) applies the absolute mean across all columns (.x means apply to current column across is on)
    summarise(across(where(is.numeric), list(mean = ~mean(abs(.x)), sd = sd))) %>%
    
    # pivot across all (will drop non numeric NAs later), then name feature/value (sd or mean)
    # (?=mean$|sd$) is a lookahead which sees what follows the underscore and then sorts 
    pivot_longer(everything(), names_to = c("feature", ".value"), names_sep = "_(?=mean$|sd$)") %>%
    drop_na()

    
# plotting
shap_p <- shap_site_summary %>%
    
    # re-orders features by most important
    ggplot(aes(x = reorder(feature, mean), y = mean, fill = mean > 0)) +
    
    geom_col(position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2) +
    
    # aesthetics
    theme_minimal() +
    ggtitle(paste("SHAP feature importance for ", ml_arch, " at all sites  (model: ", ml_model, ")", sep = "")) +
    scale_fill_manual(values = c("TRUE" = "springgreen3", "FALSE" = "tomato"), guide = "none") +
    
    # flip coords to fit in feature names easily
    coord_flip()

shap_p
```
## 3.2 trialing a function for main script (17) to form gridded plots of obs vs. fitted + SHAP feature importance in one plot

```{R}
# adjusted above to be able to select architecture, rather than facetting by it
preds_with_SHAP <- function(mod, arch, site, data, stats_df, shap_df){
    
    # get r2 and rmse form stats_df
    stats_sub <- stats_df %>%
        filter(model == mod, Site_ID == site, architecture == arch)
    
    # plot ET vs time per site
    pred_p <- data %>%
        
        filter(model == mod) %>%
        filter(Site_ID == site) %>%
        ggplot(aes(x = Date)) +
        
        # fit observed and predicted to same plot
        geom_line(aes(y = observed_ET, colour = "Observed"), alpha = 0.6) +
        geom_line(aes(y = predicted_ET, colour = "Predicted"), alpha = 0.6) +
        
        ylab("Daily ET (mm)") +
            
        ggtitle("Observed vs. Fitted") +
        
        theme_minimal()+
        
        # legend
        scale_colour_manual(name = NULL, 
                             values = c("Observed" = "seagreen", "Predicted" = "tomato")) +
        
        # move legend to bottom
        theme(legend.position = "bottom") +
            
        # add stats to plot
        geom_text(data = stats_sub,
                  aes(x = -Inf, y = Inf, 
                      label = paste("R-squared = ", round(r2, 2), 
                                     "\nRMSE = ", round(rmse, 2))),
                  hjust = -0.1, vjust = 1.2,  
                  size = 3) 
    
    
    # create df of SHAP score means across features
    shap_site_summary <- shap_df %>%
        
        # select chosen rows
        filter(Site_ID == site, architecture == arch, model == mod) %>%
        
        # apply summaries across all columns with everything()
        summarise(across(everything(), list(mean = mean, sd = sd))) %>%
        
        # pivot across all (will drop non numeric NAs later), then name feature/value (sd or mean)
        # (?=mean$|sd$) is a lookahead which sees what follows the underscore and then sorts 
        pivot_longer(everything(), names_to = c("feature", ".value"), names_sep = "_(?=mean$|sd$)") %>%
        drop_na()
    
    # and now the shap plot
    shap_p <- shap_site_summary %>%
        
        # re-orders features by most important
        ggplot(aes(x = reorder(feature, mean), y = mean, fill = mean > 0)) +
        
        geom_col(position=position_dodge()) +
        geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2) +
        
        # aesthetics
        theme_minimal() +
        xlab("Features in Model") +
        ylab("Mean SHAP value") +
        ggtitle("SHAP feature importance") +
        scale_fill_manual(name = NULL,
                          values = c("TRUE" = "steelblue", "FALSE" = "coral"), 
                          labels = c("TRUE" = "+ impact", "FALSE" = "- impact")) +
        
        # move legend to bottom
        theme(legend.position = "bottom") +
        
        # flip coords to fit in feature names easily
        coord_flip()
    
    # forming the arranged plot of the above two with patchwork lib
    final_p <- pred_p + shap_p + plot_layout(widths = c(1.3, 1)) +
          plot_annotation(title = paste(arch, " at ", site, " (model: ", mod, ")", sep = "" ))
    
    # show gridded plot
    final_p
}

```
### 3.3 Interesting result for site age at US-Syv  
- US-Syv is a very old site (300+ years old)  
- I believe this makes it the oldest site in the data  
Looking at the feature importance and R-squares vs. RMSE here for all vs. no_age models: 

```{R}
preds_with_SHAP("all", "RF", "US-Syv", preds_merged, stats_merged, shap_merged)
```
- pretty poor and over predicting a lot  
- leans on site age heavily

- and then removing age...: 

```{R}
preds_with_SHAP("no_age", "RF", "US-Syv", preds_merged, stats_merged, shap_merged)
```

- far better result when age is removed.  
- suggests at this old site that age might be leading to overfitting/noise rather than a helpful signal in the model




# Going forward  
- look into more of the plots as above (this was a brief look at some of them) 
- in some sites including stand age has a positive impact on R-squared and RMSE, whereas at others (and in more cases) it has a negative impact 
- in many it has a negligible impact on R-squared and RMSE
- this changes across model architectures significantly too
- what do these sites share on either side? - for those benefitting from age, do they have anything in common? are the models over training in closely-located and similarly-aged sites?  
- could try to make a dataset of these impacts both ways and look at correlating variables (if existing) of sites in each
- also want to form some ML models from a few other architectures if time permits  