---
title: "30_case_study_analysis2.Rmd"
output: html_document
date: "2026-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

library(tidyverse)
library(here)
library(ltc)
library(ggrepel)
library(gridExtra)
library(tikzDevice)
library(conflicted)
library(patchwork)
library(stargazer)
library(modelsummary)

# serif plots
options(tikzLatexPackages = c(
  getOption("tikzLatexPackages"),
  "\\usepackage{tgheros}",
  "\\renewcommand{\\familydefault}{\\sfdefault}",
  "\\usepackage{sansmath}",
  "\\sansmath"
))

# minion pro plots
#options(tikzLatexPackages = c(
#    getOption("tikzLatexPackages"),
#    "\\usepackage{MinionPro}\n",
#    "\\usepackage{MnSymbol}\n"
#))
```


# analysis of case study: US-Umd and DE-Lnf medoid sites  
## part 4 - manipulating site ages experiment

```{r}
conflicts_prefer(dplyr::filter)
conflicts_prefer(here::here)

df_14 <- read_csv(here("data/main/14_pre_processing/df_ml_ready.csv"))
df_stats <- read_csv(here("data/main/27_case_study/stats.csv"))
df_preds <- read_csv(here("data/main/27_case_study/preds.csv"))
df_yearly <- read_csv(here("data/main/10_filtering2/df_yearly2.csv"))

df_shap_test <- read_csv(here("data/main/27_case_study/test_shap2.csv"))
df_shap_train <- read_csv(here("data/main/27_case_study/train_shap2.csv"))

```



```{r}
# standard error function
se <- function(x) {sd(x) / sqrt(length(x))}

# colours
pal = ltc(casa_natal)

# bar plot
p1 <- df_stats %>%
    
    # group by conditions
    group_by(site, model, shuffled) %>%
    
    # stats per combination
    summarise(mean_r2 = mean(r2),
              se_r2 = se(r2),
              sd_r2 = sd(r2),
              .groups = "drop") %>%
    
    # plot bar chart with the fill as interaction between model and shuffles boolean value
    ggplot(aes(x = interaction(model, shuffled), y = mean_r2, fill = interaction(model, shuffled))) +
    
    # columns and standard error bars
    geom_col(position = "dodge", 
             width = 0.75, 
             alpha = 0.75,
             colour = "black", 
             linewidth = 0.2) +
    
    geom_errorbar(aes(ymin = mean_r2 - se_r2, ymax = mean_r2 + se_r2),
                position = position_dodge(0.9), width = 0.2) +
    
    # aesthetics
    theme_bw() +
    ylab("R$^2$") +
    scale_fill_manual(values = pal, 
                      labels = c("Mod.FALSE" = "Mod",
                                  "Mod + Age.FALSE" = "Mod + Age",
                                  "Mod + Age.TRUE" = "Mod + Shuffled Age")) +
    
    # zoom y
    coord_cartesian(ylim = c(0.75, 0.9)) +
    facet_wrap(~site) +
    xlab("") +
    theme(legend.position = "top", 
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank()) +
    labs(fill = "RF Model") 
    

p1

```

```{r}
# plot as TikZ object for integration into LaTeX
# p1
tikz(here("diss/figures/case_study_bars.tex"), width = 6, height = 4, standAlone = TRUE)
print(p1)
dev.off()

```

```{r}
summary_stats <- df_stats %>%
    
    # group by conditions
    group_by(site, model, shuffled) %>%
    
    # stats per combination
    summarise(mean_r2 = mean(r2),
              mean_mae = mean(mae),
              mean_rmse = mean(rmse),
              sd_r2 = sd(r2),
              .groups = "drop")
```

```{r}
# filter out non-training sites from .py scripts
site_col <- df_14 %>%
    filter(! Site_ID %in% c("CA-TP1", "CA-TP4", "US-Me2", "US-Me5", "US-Me6", "CH-Dav")) %>%
    select(Site_ID) 

# convert to list (def a better way to do this)
site_list <- unique(site_col$Site_ID)

# now filter yearly site data to these sites only
df_yearly_clean <- df_yearly %>%
    filter(Site_ID %in% site_list)


```


```{r}
pal = ltc(trio3)

mean_age <- df_yearly_clean %>%
    
    # for highlighting two sites
    summarise(mean_age_all = mean(Site_age))

p_age_et <- df_yearly_clean %>%
    
    filter(!Site_ID %in% c("US-UMd", "DE-Lnf")) %>%
    
    # pick one of these two
    #ggplot(aes(x = Site_age, y = ET_year)) +
    ggplot(aes(x = Site_age, y = ET_90D_peak_sum)) +
    
    theme_bw() +
    geom_point(alpha = 0.25)+
    geom_vline(xintercept = mean_age$mean_age_all, colour = "firebrick", linetype = "dashed") +
    
    # fit gam for visual aid
    geom_smooth(method = "gam", formula = y ~ s(x, k = 7), se = FALSE, alpha = 0.15, colour = pal[3])  +
    ylab("90 day peak ET sum (mm)") +
    xlab("Site Age (years)") +

    # adding in us-umd and de-lnf after plotting without them (reflects training data)
    geom_point(data = df_yearly_clean %>% 
                   filter(Site_ID %in% c("US-UMd", "DE-Lnf")),
           aes(x = Site_age, 
               
               #y = ET_year,
               y = ET_90D_peak_sum, 
               colour = Site_ID),
           
           shape = 20, fill = NA, size = 2, stroke = 1) +
    
    # colour and rename
    scale_colour_manual(
      name = "Test Site",
      values = pal
    ) 


p_age_et_ns <- df_yearly_clean %>%
    
    filter(!Site_ID %in% c("US-UMd", "DE-Lnf")) %>%
    
    # pick one of these two
    ggplot(aes(x = Site_age, y = ET_year)) +

    theme_bw() +
    geom_point(alpha = 0.25)+
    geom_vline(xintercept = mean_age$mean_age_all, colour = "firebrick", linetype = "dashed") +
    
    # fit gam for visual aid
    geom_smooth(method = "gam", formula = y ~ s(x, k = 7), se = FALSE, alpha = 0.15, colour = pal[3])  +    
    ylab("Yearly ET sum (mm)") +
    xlab("Site Age (years)") +
    #facet_wrap(~Climate_zone) +
    
    # adding in us-umd and de-lnf after plotting without them (reflects training data)
    geom_point(data = df_yearly_clean %>% 
                   filter(Site_ID %in% c("US-UMd", "DE-Lnf")),
           aes(x = Site_age, 
               
               y = ET_year,
               colour = Site_ID),
           
           shape = 20, fill = NA, size = 2, stroke = 1) +
    
    # colour and rename
    scale_colour_manual(
      name = "Test Site",
      values = pal
    ) 
    
    


p_age_et_ns
p_age_et

```


```{r}
# plot as TikZ object for integration into LaTeX
# p1
tikz(here("diss/figures/age_et_gam.tex"), width = 6, height = 4, standAlone = TRUE, sanitize = TRUE)
print(p_age_et)
dev.off()
tikz(here("diss/figures/age_et_gam_ns.tex"), width = 6, height = 4, standAlone = TRUE, sanitize = TRUE)
print(p_age_et_ns)
dev.off()
```


```{r}
# colour palette
pal = ltc(casa_natal)

p_shap_age <- bind_rows( df_shap_train %>% mutate(split = "train"), df_shap_test %>% mutate(split = NULL)) %>%
    
    # no shuffled and only age RF obviously
    filter(age_transform != "shuffled",
           model == "Mod + Age") %>%
    
    # x = raw age, y = SHAP importance for age
    ggplot(aes(x = Site_age_raw, y = Site_age)) +
    
    theme_bw() +
    
    # add in points
    geom_point(alpha = 0.3) +

    # colour and rename
    scale_colour_manual(
      name = "Test Site",
      values = pal
    ) +
    
    # mean age of all sites 
    geom_vline(xintercept = mean_age$mean_age_all, colour = "firebrick", linetype = "dashed") +

    
    # fit gam for visual aid
    #geom_smooth(method = "gam", formula = y ~ s(x, k = 10), se = FALSE, alpha = 0.25)  +

    # SHAP = 0 line
    geom_hline(yintercept = 0, colour = "black", alpha = 0.5) +
    ylab("SHAP value for \\texttt{Site\\_age}") +
    xlab("Site Age (years)") +
    
    # colour test sites 
    geom_point(data = df_shap_test %>% filter(site %in% c("US-UMd", "DE-Lnf"),
                                              model == "Mod + Age",
                                              age_transform != "shuffled"),
           aes(x = Site_age_raw, 
               
               y = Site_age,
               colour = site),
           
           shape = 20, fill = NA, stroke = 1, alpha = 0.3)
    

p_shap_age
```


```{r}
tikz(here("diss/figures/shap_dependence.tex"), width = 6, height = 4, standAlone = TRUE)
print(p_shap_age)
dev.off()
```


```{r}
# fit the same gam as in the plot and see if significant or not


```

